import { Providers } from "./utils/provider";
import Context from "./utils/context";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen">
        <Providers>
          <Context>{children}</Context>
        </Providers>
      </body>
    </html>
  );
}
